# Generated by Django 5.2.2 on 2025-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Pending', max_length=50),
        ),
    ]
